version: '2.0' # docker-compose version

networks:
  dnet1:
    external: true

services:
  db:
    build:
      context: ./postgis
      dockerfile: Dockerfile_postgis
    restart: always
    environment:
      POSTGRES_USER: road
      POSTGRES_PASSWORD: road
      POSTGRES_DB: road
    networks:
      - dnet1
    ports:
      - 54322:5432
    command: -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.max=10000 -c track_activity_query_size=2048 -c pg_stat_statements.track=all -c max_connections=200

  db-init:
    image: flyway/flyway:9.3-alpine
    networks:
      - dnet1
    volumes:
      - "./sql:/flyway/sql"
      - "./files:/flyway/conf"
    links:
      - "db:db"
    command: "migrate"
    depends_on:
      - db

  pghero:
    image: ankane/pghero
    restart: always
    networks:
      - dnet1
    environment:
      DATABASE_URL: postgres://road:road@db:5432/road
    links:
      - "db:database" # postgres is reachable for pghero from web at the hostnames db and database
    ports:
      - 8082:8080
    depends_on:
      - db