version: '2.1'

networks:
  dnet1:
    external: true

services:
  db:
    image: postgres:12.9-alpine
    restart: always
    environment:
      POSTGRES_USER: road
      POSTGRES_PASSWORD: road
      POSTGRES_DB: road
    networks:
      - dnet1
    command: -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.max=10000 -c track_activity_query_size=2048 -c pg_stat_statements.track=all -c max_connections=200
    build:
      context: ./postgis
      dockerfile: Dockerfile_postgis