version: '2.0' # docker-compose version

networks:
  db_network:
    external:
      name: dnet1

services:
  db:
    image: postgres:9.6.11
    restart: always
    environment:
      POSTGRES_USER: road
      POSTGRES_PASSWORD: road
      POSTGRES_DB: road
    networks:
      - db_network

  db-wait:
      build: .
      networks:
          - db_network
      links:
          - "db:db"
      command: ["./wait-for-postgres.sh", "db", "marine", "marine", "marine"]