version: '2.1'

networks:
  db_network:
    external:
      name: dnet1

services:
  db:
    image: postgres:9.6.12-alpine
    restart: always
    environment:
      POSTGRES_USER: road
      POSTGRES_PASSWORD: road
      POSTGRES_DB: road
    networks:
      - db_network