version: '2.1'

networks:
  db_network:
    external:
      name: dnet1

services:
  db:
    image: postgres:9.6.12-alpine
    restart: always
    environment:
      POSTGRES_USER: road
      POSTGRES_PASSWORD: road
      POSTGRES_DB: road
    networks:
      - db_network

  db-wait:
      build: .
      depends_on:
        - db
      networks:
        - db_network
      links:
        - "db:db"
      command: ["./wait-for-postgres.sh", "db", "road", "road", "road"]