version: '2.0' # docker-compose version

services:

  db:
    image: postgres:9.6.8
    restart: always
    environment:
      POSTGRES_USER: road
      POSTGRES_PASSWORD: road
      POSTGRES_DB: road
    ports:
      - 54322:5432
    command: -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.max=10000 -c track_activity_query_size=2048 -c pg_stat_statements.track=all

  db-init:
    build: .
    volumes:
      - "./sql:/sql"
      - "~/.m2:/root/.m2"
    links:
      - "db:db"
    command: ["./wait-for-postgres.sh", "db", "road", "road", "road", "./init-db.sh"]