name: Update Fargate Service
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        type: environment
        default: 'test'
      family-name:
        description: 'Which service to update'
        required: true
        type: choice
        options:
          - road-daemon
          - road-web
          - road-db
      ci-repo-branch:
        description: 'Which branch/tag of ci-repo to use'
        type: string
        required: true
        default: 'master'

jobs:
  update:
    name: Update task
    environment: ${{ github.event.inputs.env }}
    uses: tmfg/digitraffic-actions/.github/workflows/update-ecs-service-action.yml@ecs-service-update/v1
    with:
      ci-repo-branch: ${{ github.event.inputs.ci-repo-branch }}
      family-name: ${{ github.event.inputs.family-name }}
      asw-role: ${{ secrets.AWS_ROLE }}
    secrets:
        CI_REPO_URL: ${{ secrets.CI_REPO_URL }}
        CI_SSH_KEY: ${{ secrets.CI_SSH_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

