name: Update Fargate Service
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        type: environment
        default: 'test'
      family-name:
        description: 'Which service to update'
        required: true
        type: choice
        options:
          - road-daemon
          - road-web
          - road-db
      revision:
        description: 'Which revision to install'
        type: string
        required: true
        default: 'latest'

jobs:
  update:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    steps:
        - name: Update
          uses: tmfg/digitraffic-actions@ecs-service-update/v1
          with:
            revision: ${{ inputs.revision }}
            family-name: ${{ github.event.inputs.family-name }}
            asw-role: ${{ secrets.AWS_ROLE }}
            cluster-name: ${{ secrets.CLUSTER_NAME }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

