name: Update Fargate Service
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        type: environment
        default: 'test'
      family-name:
        description: 'Which service to update'
        required: true
        type: choice
        options:
          - daemon
          - web
          - db
      revision:
        description: 'Which revision to install'
        type: string
        required: true
        default: 'latest'

jobs:
  update:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Update
        uses: tmfg/digitraffic-actions@ecs-service-update/v1
        with:
          revision: ${{ github.event.inputs.revision }}
          service-name: road-${{ github.event.inputs.family-name }}-${{ github.event.inputs.env }}
          aws-role: ${{ secrets.AWS_ROLE }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

